spring:
  main:
    banner-mode: off
  application:
    name: 'places'
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
